title: Wyre Transfer Bot
tagline: The bot that allows you to send money between China and other countries.
author:
  name : Wyre
  url : "https://www.sendwyre.com/"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

sass:
    sass_dir: _sass
